
development:
  client_id: 175290
  client_secret: fb0167863f
  account_id: 353008
  access_token: b009f8dac83038f2df195a9197470543ab36e4c8a8b3059eba8057138616b13d
  root_callback_uri: "http://www.deelmob.com"
  after_checkout_redirect_uri: "/site-manager"
  scope: [refund_payments,collect_payments,view_balance,view_user]
  wepay_ui_endpoint: "https://stage.wepay.com/v2"
  wepay_api_endpoint: "https://stage.wepayapi.com/v2"
  fee_payer: payee
  charge_tax: false
  app_fee: 0
  require_shipping: false
  shipping_fee: 0
  charge_tax: false
  preapproval_auto_recur: true


test:
  client_id: 157742
  client_secret: ddb30ff687
  account_id: 222888
  access_token: f93f97d90ef24178a906ac518357868ff6c4b0f5ff7103c570a6c0f68fbf1849
  root_callback_uri: "http://www.deelmob.com"
  after_checkout_redirect_uri: "/site-manager"
  scope: [refund_payments,collect_payments,view_balance,view_user]
  wepay_ui_endpoint: "https://www.wepay.com/v2"
  wepay_api_endpoint: "https://www.wepayapi.com/v2"
  fee_payer: payee
  charge_tax: false
  app_fee: 0
  require_shipping: false
  shipping_fee: 0
  charge_tax: false
  preapproval_auto_recur: true


production:
  client_id: 157742
  client_secret: ddb30ff687
  account_id: 222888
  access_token: f93f97d90ef24178a906ac518357868ff6c4b0f5ff7103c570a6c0f68fbf1849
  root_callback_uri: "http://www.yomobi.com"
  after_checkout_redirect_uri: "/site-manager"
  scope: [refund_payments,collect_payments,view_balance,view_user]
  wepay_ui_endpoint: "https://www.wepay.com/v2"
  wepay_api_endpoint: "https://www.wepayapi.com/v2"
  fee_payer: payee
  charge_tax: false
  app_fee: 0
  require_shipping: false
  shipping_fee: 0
  charge_tax: false
  preapproval_auto_recur: true

