# production:
#   client_id: <your client id from wepay>
#   client_secret: <your client secret from wepay>
#   account_id: <your account id from wepay>
#   access_token: <your access token that you recieved when you went to http://your.domain.com/wepay/authorize>
#   root_callback_uri: "http://www.example.com"
#   after_checkout_redirect_uri: "http://www.example.com/purchase/finalize"
#   scope: [refund_payments,collect_payments,view_balance,view_user]
#   wepay_api_uri: "https://api.wepay.com/v2"
#   fee_payer: Payee
#   checkout_type: GOODS
#   charge_tax: false
#   app_fee: 0
#   auto_capture: true
#   require_shipping: false
#   shipping_fee: 0
#   charge_tax: false
development:
  client_id: 175290
  client_secret: fb0167863f
  account_id: 353008
  access_token: b009f8dac83038f2df195a9197470543ab36e4c8a8b3059eba8057138616b13d
  root_callback_uri: "http://www.local.host:3000"
  after_checkout_redirect_uri: "http://www.local.host:3000/account/payments"
  scope: [refund_payments,collect_payments,view_balance,view_user]
  wepay_api_uri: "http://stage.wepayapi.com/v2"
  fee_payer: Payee
  checkout_type: SERVICE
  charge_tax: false
  app_fee: 0
  auto_capture: true
  require_shipping: false
  shipping_fee: 0
  charge_tax: false
