- { name: about-us, pname: about-us }
- { name: blog, pname: blog }
- { name: booking-request, pname: booking-request }
- { name: business-hours, pname: business-hours }
- { name: call-me-back, pname: call-me-back }
- { name: call-us, pname: call-us }
- { name: category, pname: category }
- { name: coupon, pname: coupon }
- { name: custom-page, pname: custom-page }
- { name: donate, pname: donate }
- { name: event-calendar, pname: event-calendar }
- { name: facebook, pname: facebook }
- { name: find-us, pname: find-us }
- { name: flickr, pname: flickr }
- { name: full-website, pname: full-website }
- { name: keep-me-informed, pname: keep-me-informed }
- { name: leave-a-message, pname: leave-a-message }
- { name: link, pname: link }
- { name: listings, pname: listings }
- { name: locations, pname: locations }
- { name: menu, pname: menu }
- { name: news, pname: news }
- { name: photo-bucket, pname: photo-bucket }
- { name: photos, pname: photos }
- { name: picasa, pname: picasa }
- { name: products, pname: products }
- { name: property-listings, pname: property-listings }
- { name: reviews, pname: reviews }
- { name: services, pname: services }
- { name: share, pname: share }
- { name: tell-a-friend, pname: tell-a-friend }
- { name: twitter, pname: twitter }
- { name: video, pname: video }
