link::video:
  canRename: true
  canEditIcon: true
link_fb::twitter:
  canRename: true
  canEditIcon: true
tell_friend::tell-a-friend:
  canRename: true
  canEditIcon: true
category::services:
  canRename: true
  canEditIcon: true
link::reviews:
  canRename: true
  canEditIcon: true
category::property-listings:
  canRename: true
  canEditIcon: true
category::products:
  canRename: true
  canEditIcon: true
link_fb::picasa:
  canRename: true
  canEditIcon: true
link::photo-bucket:
  canRename: true
  canEditIcon: true
link::news:
  canRename: true
  canEditIcon: true
category::menu:
  canRename: true
  canEditIcon: true
category::locations:
  canRename: true
  canEditIcon: true
link::link:
  canRename: true
  canEditIcon: true
leave_msg::leave-a-message:
  canRename: true
  canEditIcon: true
informed::keep-me-informed:
  canRename: true
  canEditIcon: true
link::full-website:
  canRename: true
  canEditIcon: true
link_fb::flickr:
  canRename: true
  canEditIcon: true
gmap::find-us:
  canRename: true
  canEditIcon: true
link_fb::facebook:
  canRename: true
  canEditIcon: true
link::event-calendar:
  canRename: true
  canEditIcon: true
link::donate:
  canRename: true
  canEditIcon: true
custom_page::custom-page:
  canRename: true
  canEditIcon: true
coupon::coupon:
  canRename: true
  canEditIcon: true
page_tree::category:
  canRename: true
  canEditIcon: true
phone::call-us:
  canRename: true
  canEditIcon: true
call_back::call-me-back:
  canRename: true
  canEditIcon: true
hours::business-hours:
  canRename: true
  canEditIcon: true
booking::booking-request:
  canRename: true
  canEditIcon: true
link::blog:
  canRename: true
  canEditIcon: true
custom_page::about-us:
  canRename: true
  canEditIcon: true
rss::rss-feed:
  canRename: true
  canEditIcon: true
